import { Button, TextEdit, LineEdit } from "std-widgets.slint";
import {List} from "list.slint";
import { HorizontalBox , VerticalBox, GridBox} from "std-widgets.slint";
import { Todo} from "./types.slint";

export component Main inherits Window {
    in-out property <[Todo]> todos;
    callback add-todo(string);
    callback get-todos();

    width: 1000px;
    height: 500px;
    HorizontalLayout {
        aside := VerticalLayout {
            height: root.height;
            alignment: start;
            width: 300px;
            spacing: 5px;
            VerticalBox {
                input := LineEdit {
                    height: 30px;
                    font-size: 14px;
                    placeholder-text: "new todo";
                    horizontal-alignment: center;
                }

                GridBox {
                    Rectangle {
                        border-radius: 20px;
                        Button {
                            height: 30px;
                            clicked => {
                                root.add-todo(input.text);
                                input.text = "";
                            }
                            text: "Add new";
                            primary: true;
                        }
                    }

                    Rectangle {
                        border-radius: 20px;
                        Button {
                            clicked => {
                                root.get-todos();
                            }
                            text: "Refresh";
                        }
                    }
                }
            }
        }

        main := VerticalLayout {
            width: 700px;
            list := List {
                todos: todos;
            }
        }
    }
}
